### ISSUE TITLE
Fix gitflow from dev-torch

### ISSUE THREAD

**Issue by DrJonnyT** [AI-Fundamentals/DiffPrivNPUserModeling#12]
I merged from dev-torch to main. Reverted that PR as I wanted to do it via. Merged dev-torch into development. Merged development into main. Now main says it has merged all the changes but if you look at the files, it actually hasn't.

Possible solution- hard reset main back to 26fd7fc then do a new PR from development. I think that should be the way it's supposed to work

**Comment by jiawu-2** [comment]
I agree with you, Jonny. The hard reset is the way to fix it.

**Comment by DrJonnyT** [comment]
OK I'll very carefully give it a go 😅

**Comment by DrJonnyT** [comment]
Sorted, I actually did a hard reset on main to the commit at which I created the feature branch dev-torch branch, which was further back. I've also changed the default branch to development and deleted dev-torch
